name: CI/CD for Static Website

on:
  push:
    branches:
      - main  # Triggers the workflow on every push to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running basic tests..."
          if [ -f index.html ]; then
            echo "✅ index.html found!"
          else
            echo "❌ index.html is missing!"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Deploy only if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Website to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./*"  # Upload everything in the repo
          target: "/home/ubuntu/static-website"

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo apt update && sudo apt install -y nginx
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/static-website/* /var/www/html/
            sudo systemctl restart nginx