name: Deploy Static Website

on:
  push:
    branches: [ "main" ]  # Runs on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Website to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./*"  # Upload everything in the repo
          target: "/home/ubuntu/static-website"

      - name: Configure Nginx and Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo apt update && sudo apt install -y nginx
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/static-website/* /var/www/html/
            sudo systemctl restart nginx

    